### ISSUE TITLE
Add scale in degrees Celsius.

### ISSUE THREAD

**Issue by arnav-t** [arnav-t/insat-clouds#7]
Look into weather it can be changed via API calls or superimpose it manually on the images.

**Comment by mm-git01** [comment]
does one have to apply for this via kwoc officially or will it be okay if i send a pr without a proposal ?

**Comment by arnav-t** [comment]
@Pac23 It's fine if you have already registered as a student on the website. All your contributions will be tracked automatically.

**Comment by arnav-t** [comment]
The registrations are still open, by the way (if you haven't applied yet).

**Comment by mm-git01** [comment]
@arnav-t  done!

**Comment by mm-git01** [comment]
@arnav-t do you want to keep the first k scale and add the Celsius one or replace k with C*

**Comment by arnav-t** [comment]
@Pac23 Whatever's more convenient. The Kelvin scale is not really needed.

**Comment by mm-git01** [comment]
@arnav-t done check PR #8 

I have updated urllib with requests as well also removed the requirement of editing the path manually,now it simply takes the absolute path using the os.path module.

**Comment by arnav-t** [comment]
Added in #8
